openapi: 3.0.1
info:
  description: Swagger documentation for the Value Added Services APIs
  title: VAS API
  version: '1.0'
servers:
  - url: /
security:
  - open_id_scheme:
      - read
      - write
paths:
  /api/sharing/getAllRatingsForCompany:
    get:
      operationId: getAllRatingsForCompany
      parameters:
        - in: query
          name: year
          required: false
          schema:
            default: 0
            format: int32
            type: integer
        - in: query
          name: companyUserDTO
          required: true
          schema:
            $ref: '#/components/schemas/CompanyUserDTO'
      responses:
        '200':
          content:
            '*/*':
              schema:
                default: []
                items:
                  $ref: '#/components/schemas/DataSourceDTO'
                maxItems: 20
                type: array
          description: Ratings of inserted custom year retrieved with success
        '401':
          description: Authentication Required
      security:
        - bearerAuth: []
        - open_id_scheme: []
      summary: Retrieves ratings based on inserted year and Company User
      tags:
        - Sharing Controller
  /api/sharing/getAllRatingsScoresForEachBpn:
    get:
      operationId: getAllRatingsScoresForEachBpn
      parameters:
        - name: datasource[]
          in: query
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/InputSharingDataSourceDTO'
            maxItems: 20
            default: []
        - name: bpns[]
          in: query
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/InputSharingBusinessPartnerDTO'
            maxItems: 20
            default: []
        - name: companyUser
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/CompanyUserDTO'
      responses:
        '200':
          content:
            '*/*':
              schema:
                default: []
                items:
                  $ref: '#/components/schemas/ShareDTO'
                maxItems: 20
                type: array
          description: Ratings of inserted custom year retrieved with success
        '401':
          description: Authentication Required
      security:
        - bearerAuth: []
        - open_id_scheme: []
      summary: Retrieves Mapped ratings to the Business Partners based on inserted
        year, Company User, Ratings, BPN
      tags:
        - Sharing Controller
components:
  schemas:
    CompanyUserDTO:
      required:
        - companyName
        - email
        - name
      type: object
      properties:
        name:
          type: string
          example: John
        email:
          type: string
          example: John@email.com
        companyName:
          type: string
          example: TestCompany
    InputSharingDataSourceDTO:
      required:
        - dataSourceName
        - yearPublished
      type: object
      properties:
        dataSourceName:
          type: string
          example: Fake Rating
        yearPublished:
          type: integer
          format: int32
          example: 2021
    InputSharingBusinessPartnerDTO:
      type: object
      properties:
        bpn:
          type: string
          example: BPN-NUMBER
        country:
          type: string
          example: Portugal
    ShareDTO:
      additionalProperties: false
      properties:
        bpn:
          example: BPN-NUMBER
          type: string
        country:
          example: Portugal
          type: string
        id:
          format: int64
          type: integer
        iso2:
          example: PT
          type: string
        rating:
          default: []
          items:
            $ref: '#/components/schemas/ShareRatingDTO'
          maxItems: 20
          type: array
      type: object
    ShareRatingDTO:
      type: object
      properties:
        dataSourceName:
          type: string
          example: Fake Rating
        score:
          type: number
          format: float
          example: 100
        yearPublished:
          type: integer
          format: int32
          example: 2021
    DataSourceDTO:
      required:
        - dataSourceName
        - type
        - yearPublished
      type: object
      properties:
        id:
          type: integer
          format: int64
        dataSourceName:
          type: string
          example: Fake Rating
        type:
          type: string
          example: Custom
          enum:
            - Global
            - Custom
            - Company
        yearPublished:
          type: integer
          format: int32
          example: 2021
        fileName:
          type: string
          example: Test Company Rating
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
    open_id_scheme:
      flows:
        authorizationCode:
          authorizationUrl: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/auth
          scopes:
            admin: Grants access to admin operations
            read: Grants read access
            write: Grants write access
          tokenUrl: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      type: oauth2

